services:
  - type: web
    name: amazon-scraper
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
