services:
  - type: web
    name: amazon-scraper
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: node index.js
    autoDeploy: true
